export const ROLES = [
  'Accountant',
  'Business Analyst',
  'Cloud Architect',
  'Content Strategist',
  'Customer Support Specialist',
  'Data Analyst',
  'Data Scientist',
  'Database Administrator',
  'Desktop Support Technician',
  'DevOps Engineer',
  'Frontend Developer',
  'Fullstack Developer',
  'Game Developer',
  'Graphic Designer',
  'HR Generalist',
  'IT Support Specialist',
  'Marketing Specialist',
  'Mobile Developer (Android)',
  'Mobile Developer (iOS)',
  'Motion Designer',
  'Network Engineer',
  'Operations Manager',
  'Product Manager',
  'Project Manager',
  'Quality Assurance (QA) Engineer',
  'Recruiter',
  'Research Analyst',
  'Sales Representative',
  'Scrum Master',
  'Security Analyst',
  'SEO Specialist',
  'Social Media Manager',
  'Solutions Architect',
  'Systems Analyst',
  'Technical Writer',
  'UI Designer',
  'UX Designer',
  'AR/VR Developer',
  'ML Engineer',
];

export default ROLES;
